server:
  port: 8082
  servlet:
    context-path: /eagle-admin
  tomcat:
      uri-encoding: utf-8
  # HTTP请求和响应头的最大量，以字节为单位，默认值为4096字节,超过此长度的部分不予处理,一般8K。解决java.io.EOFException: null问题
  max-http-header-size: 8192
  use-forward-headers: true
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    # 配置thymeleaf修改页面不重启生效
    cache: false
    encoding: utf-8
    mode: LEGACYHTML5
  datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.31.1.105:3307/eagle?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: szqbdev
      password: szqb@dev
      type: com.alibaba.druid.pool.DruidDataSource
      initial-size: 1
      minIdle: 3
      maxActive: 20
      maxWait: 60000
      filters: stat,wall,slf4j
  # Redis
  redis:
    database: 0
    host: 127.0.0.1
    #集群配置
    #host: 10.31.1.128:7000,10.31.1.128:7001,10.31.1.128:7002,10.31.1.128:7003,10.31.1.128:7004,10.31.1.128:7005
    port: 6379
    #密码默认为空，注释即可，要添加密码，去掉注释添加就行
   # password: LLOOGG
    pool: #star
      maxActive: 8
      maxWait: -1
      maxIdle: 8
      minIdle: 0 #end
    # 连接超时时间（毫秒）
    timeout:  3000
    # 默认的数据过期时间，主要用于shiro权限管理
    expire: 2592000
  profiles:
    active: dev
  application:
      name: eagle-admin
  #增加加密的key配置：响应数据需要加密的话，就在Controller的方法上加@Encrypt注解即可。需要解密的操作我们加上@Decrypt注解即可。
  encrypt:
      #加密key，必须是16位
      key: abcdef0123456789
      #是否开启调试模式,默认为false,如果为true则不启用加解密操作
      debug: true
mybatis:
    type-aliases-package: org.eagle.admin.sys.entity
    mapper-locations: classpath:/mapper/sys/*.xml
mapper:
    mappers:
        - org.eagle.core.mybatis.mapper.BaseMapper
    not-empty: false
    identity: MYSQL
pagehelper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true
    params: count=countSql
logging:
    file: ./logs/log.log
    level:
      com.hope: DEBUG
      tk.mybatis: DEBUG
      org.springframework: WARN

#自定义配置
eagle:
  shiro:
    # 后端免认证接口 url
    anonUrl: /login,/logout/**,/regist,/user/check/**
    # token有效期，单位秒
    jwtTimeOut: 3600

#swagger入口： http://localhost:8082/eagle-admin/swagger-ui.html#/
