# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8081
  servlet:
    context-path: /eagle-admin

spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

mybatis:
    type-aliases-package: com.eagel.admin.*.entity
    mapper-locations: classpath:/mybati/*/*.xml
mapper:
    mappers:
        - org.eagle.core.mybatis.mapper.BaseMapper
    not-empty: false
    identity: MYSQL
pagehelper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true
    params: count=countSql
logging:
    file: ./logs/log.log
    level:
      org.eagel: DEBUG
      tk.mybatis: DEBUG
      org.springframework: WARN
